# Numpy Basic Operations

In [1]:
import numpy as n

In [2]:
# arange() range(m,n) 0,n-1 m,n-1

In [3]:
n.arange(5) # 0,1,2,3,4

array([0, 1, 2, 3, 4])

In [4]:
n.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
n.arange(1,10,5) # 1,3,5,7,9

array([1, 6])

In [12]:
n.linspace(4,10,num=10,endpoint=False)

array([4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2, 8.8, 9.4])

In [17]:
arr = n.arange(8)
arr1 = n.reshape(arr,(2,4))

In [18]:
n.transpose(arr1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [19]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
n.zeros((2,4),dtype=n.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [25]:
n.ones(4)

array([1., 1., 1., 1.])

In [26]:
arr1.shape

(2, 4)

In [27]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])